# Set update schedule for GitHub Actions

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
    labels:
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
    labels:
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "coq-8.20"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
    labels:
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "coq-8.19"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
    labels:
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "coq-8.18"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
    labels:
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "coq-8.17"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
    labels:
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "coq-8.16"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
    labels:
      - "dependencies"
