dist: trusty
sudo: required
language: c
cache:
  apt: true
  directories:
  - $HOME/.opam

addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud

env:
  global:
  - NJOBS=2
  - COMPILER="4.06.1"
  - CAMLP5_VER="7.05"
  - FINDLIB_VER="1.8.0"
  - COQ_VER="8.8.0"

install:
- opam init -j ${NJOBS} -n -y --compiler=$COMPILER
- opam switch set ${COMPILER}
- eval $(opam config env)
- opam config list
- opam update
- opam install -j ${NJOBS} -y camlp5.${CAMLP5_VER} ocamlfind.${FINDLIB_VER} coq.${COQ_VER} coq-equations
- opam list

script:
 - make -j ${NJOBS} all test-suite

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1d832177d55504ef1fba
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
